"""add_affiliate_commerce_module

Revision ID: c6534927a384
Revises: 6a7025e418a9
Create Date: 2026-07-09 16:30:17.191581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6534927a384'
down_revision: Union[str, None] = '6a7025e418a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.Enum('AMAZON_US', 'AMAZON_BR', name='marketplaceenum'), nullable=False),
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('affiliate_url', sa.String(), nullable=False),
    sa.Column('associate_tag', sa.String(), nullable=False),
    sa.Column('price_text', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_products_asin'), 'affiliate_products', ['asin'], unique=False)
    op.create_index(op.f('ix_affiliate_products_id'), 'affiliate_products', ['id'], unique=False)
    op.create_table('affiliate_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('hook_1', sa.Text(), nullable=True),
    sa.Column('hook_2', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('trigger_keyword', sa.String(), nullable=True),
    sa.Column('seo_tags', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', name='contentstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['affiliate_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_contents_id'), 'affiliate_contents', ['id'], unique=False)
    op.alter_column('contents', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contents', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contents', 'performance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('event_logs', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event_logs', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trends', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trends', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trends', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'name')
    op.alter_column('trends', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trends', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trends', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event_logs', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event_logs', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contents', 'performance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('contents', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contents', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_affiliate_contents_id'), table_name='affiliate_contents')
    op.drop_table('affiliate_contents')
    op.drop_index(op.f('ix_affiliate_products_id'), table_name='affiliate_products')
    op.drop_index(op.f('ix_affiliate_products_asin'), table_name='affiliate_products')
    op.drop_table('affiliate_products')
    # ### end Alembic commands ###
